name: Build
on:
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/**'
      - 'src/**'
      - 'action.yaml'
      - 'package-lock.json'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Create release build
        run: |
          npm install
          npm run build:prod
      - name: Push to GitHub
        uses: EndBug/add-and-commit@v9.1.1
        with:
          add: '-f ./dist'
          author_name: 'GitHub Actions'
          author_email: 'action@github.com'
          message: 'build: Build action'
