name: Build and Commit

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'dist/**'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install dependencies
      run: npm ci

    - name: Build for production
      run: npm run build:prod

    - name: Check for changes
      id: git_status
      run: |
        git diff --quiet dist || echo "changes=true" >> $GITHUB_OUTPUT

    - name: Commit and push built files
      if: steps.git_status.outputs.changes == 'true'
      uses: EndBug/add-and-commit@v7
      with:
        add: 'dist'
        message: 'Add built files [skip ci]'
        push: ${{ github.ref == 'refs/heads/master' }}

    - name: Check if build was skipped
      if: steps.git_status.outputs.changes != 'true'
      run: echo "No changes in dist directory. Skipping commit."
